### ISSUE TITLE
help, NPC disappears if hit

### ISSUE THREAD

**Issue by jadperr** [DaisukeDaisuke/npcForm#5]
In survival mode, the NPC will disappear if hit several times. and disappears when hit in creative mode.
please fix this...

**Comment by DaisukeDaisuke** [comment]
>  I use google translation.

Thank you for your report.
 Are you using the latest commit?

I think that the NPC disappearance bug in the creative mode is mainly a Minecraft specification.
Continue the investigation....

NPC disappears when attacking NPC in creative mode
#2

**Comment by jadperr** [comment]
> > I use google translation.
> 
> Thank you for your report.
> Are you using the latest commit?
> 
> I think that the NPC disappearance bug in the creative mode is mainly a Minecraft specification.
> Continue the investigation....
> 
> NPC disappears when attacking NPC in creative mode
> #2

yes i use the latest commit. I tried it in survival mode and hit npc 20 times, then it disappeared

**Comment by DaisukeDaisuke** [comment]
> I use google translation and deepl translation .

I deeply apologize for the delay in responding to you.
I apologize for not being able to reproduce this issue.
